Repository LiskHQ/lisk-commander, pull requests merged in 2018-03, with the labels that each got.

#463 Update readme to match standard
  README.md
Labels: in progress

#418 Create transactions without signature - Closes #388
  src/commands/create_transaction_cast_votes.js
  src/commands/create_transaction_register_delegate.js
  src/commands/create_transaction_register_multisignature_account.js
  src/commands/create_transaction_register_second_passphrase.js
  src/commands/create_transaction_transfer.js
  src/utils/options.js
  test/specs/commands/create_transaction_cast_votes.js
  test/specs/commands/create_transaction_register_delegate.js
  test/specs/commands/create_transaction_register_multisignature_account.js
  test/specs/commands/create_transaction_register_second_passphrase.js
  test/specs/commands/create_transaction_transfer.js
  test/steps/inputs/1_given.js
  test/steps/options/1_given.js
  test/steps/transactions/3_then.js
Labels: pending review

#422 Verify message command - Closes #59
  src/commands/verify_message.js
  src/utils/cryptography.js
  test/specs/commands/verify_message.js
  test/specs/utils/crypto_module.js
  test/steps/crypto/1_given.js
  test/steps/crypto/2_when.js
  test/steps/crypto/3_then.js
  test/steps/inputs/1_given.js
  test/steps/setup.js
  test/steps/utils.js
  test/steps/vorpal/2_when.js
Labels: ready

#466 Fix recursive to have limit and catch failed API - Closes #452
  src/utils/error.js
  src/utils/query.js
  src/utils/tablify.js
  test/specs/utils/error.js
  test/specs/utils/query.js
  test/specs/utils/tablify.js
  test/steps/general/1_given.js
  test/steps/general/2_when.js
  test/steps/general/3_then.js
  test/steps/printing/2_when.js
  test/steps/printing/3_then.js
  test/steps/queries/1_given.js
  test/steps/queries/2_when.js
  test/steps/setup.js
Labels: ready
