Repository LiskHQ/lisk-commander, pull requests merged in 2018-04, with the labels that each got.

#471 Fix register multisignature appending plus - Closes #470
  src/commands/create_transaction_cast_votes.js
  src/commands/create_transaction_register_multisignature_account.js
  src/utils/helpers.js
  test/specs/commands/create_transaction_cast_votes.js
  test/specs/utils/helpers.js
  test/steps/domain/1_given.js
  test/steps/domain/2_when.js
  test/steps/domain/3_then.js
  test/steps/general/3_then.js
  test/steps/printing/2_when.js
  test/steps/queries/1_given.js
  test/steps/queries/2_when.js
  test/steps/queries/3_then.js
  test/steps/setup.js
  test/steps/transactions/3_then.js
Labels: ready

#417 Add dot notation to the config file - Closes #347
  default_config.json
  src/commands/set.js
  src/utils/api.js
  src/utils/constants.js
  test/specs/commands/set.js
  test/specs/utils/api.js
  test/steps/config/1_given.js
  test/steps/files/1_given.js
Labels: ready

#476 Fix printing the array of objects - Closes #474
  src/utils/print.js
  test/specs/utils/print.js
  test/steps/printing/1_given.js
  test/steps/printing/2_when.js
  test/steps/printing/3_then.js
Labels: pending review

#480 Add set network command and remove testnet options - Closes #477
  default_config.json
  package.json
  src/commands/get.js
  src/commands/list.js
  src/commands/set.js
  src/utils/api.js
  src/utils/constants.js
  src/utils/options.js
  src/utils/query.js
  test/specs/commands/set.js
  test/specs/utils/api.js
  test/specs/utils/query.js
  test/steps/api/3_then.js
  test/steps/config/1_given.js
  test/steps/config/3_then.js
Labels: ready

#483 Fix tablify of nested object - Closes #475
  src/utils/tablify.js
  test/specs/utils/tablify.js
  test/steps/general/1_given.js
  test/steps/printing/3_then.js
Labels: pending review

#479 Update Node.js to 6.14.1 - Closes #478
  .nvmrc
  package.json
Labels: ready

#484 Convert amount in transfer - Closes #482
  src/commands/create_transaction_transfer.js
  src/utils/helpers.js
  test/specs/commands/create_transaction_transfer.js
  test/specs/utils/helpers.js
  test/steps/domain/1_given.js
  test/steps/domain/2_when.js
  test/steps/domain/3_then.js
  test/steps/transactions/3_then.js
Labels: ready

#488 Include private key in create account - Closes #486
  src/commands/create_account.js
  test/README.md
  test/specs/commands/create_account.js
  test/steps/crypto/3_then.js
Labels: ready

#489 Bump cli-table2 to use latest GitHub commit - Closes #487
  package.json
Labels: ready

#490 Update config from api.node to api.nodes - Closes #481
  default_config.json
  src/commands/set.js
  src/utils/api.js
  src/utils/constants.js
  test/specs/commands/set.js
  test/specs/utils/api.js
  test/steps/api/2_when.js
  test/steps/config/1_given.js
  test/steps/config/3_then.js
  test/steps/files/1_given.js
  test/steps/inputs/1_given.js
  test/steps/utils.js
  test/steps/vorpal/2_when.js
Labels: ready

#495 Update vorpal to 1.0.0 version - Closes #492
  package.json
Labels: ready

#500 Correct set command error message - Closes #498
  src/commands/set.js
  test/specs/commands/set.js
Labels: ready

#496 Add FAQ section to README - Closes #465
  README.md
Labels: ready

#504 Remove circular dependency in utils - Closes #501
  src/utils/config.js
  src/utils/helpers.js
  src/utils/logger.js
  src/utils/print.js
  test/specs/utils/logger.js
  test/specs/utils/print.js
  test/steps/config/3_then.js
  test/steps/printing/2_when.js
  test/steps/setup.js
Labels: pending review

#502 Validate config on load - Closes #493
  src/utils/config.js
  test/specs/utils/config.js
  test/steps/config/3_then.js
  test/steps/files/1_given.js
Labels: ready

#505 Use LiskHQ cli-table2 dependency - Closes #503
  package.json
Labels: ready

#513 Update lisk-js to 1.0.0 beta.2 - Closes #511
  package.json
  src/utils/api.js
  test/specs/utils/api.js
Labels: pending review

#506 Add validation on api.nodes url
  src/commands/set.js
  src/utils/constants.js
  test/specs/commands/set.js
Labels: in progress

#515 Update passphrase encryption - Closes #497
  src/commands/decrypt_passphrase.js
  src/utils/cryptography.js
  test/specs/commands/decrypt_passphrase.js
  test/specs/utils/cryptography.js
  test/steps/crypto/1_given.js
  test/steps/crypto/2_when.js
  test/steps/crypto/3_then.js
  test/steps/inputs/1_given.js
  test/steps/setup.js
  test/steps/vorpal/2_when.js
Labels: ready
