Repository LiskHQ/lisk-commander, pull requests merged in 2018-05, with the labels that each got.

#520 Update Jenkinsfile for slack integration
  Jenkinsfile
Labels: ready

#526 Add sign transaction - Closes #406
  src/commands/sign_transaction.js
  test/specs/commands/sign_transaction.js
  test/steps/setup.js
  test/steps/transactions/3_then.js
  test/steps/utils.js
  test/steps/vorpal/2_when.js
Labels: ready

#534 Add timeout to readline - Closes #528
  src/utils/input/utils.js
Labels: ✅ ready

#537 Update vorpal version - Closes #531
  package.json
Labels: :eye: pending review

#536 Change table style - Closes #535
  src/utils/error.js
  src/utils/tablify.js
  test/specs/utils/error.js
  test/specs/utils/tablify.js
  test/steps/general/3_then.js
  test/steps/printing/3_then.js
Labels: ✅ ready

#533 Fix lockfile usage - Closes #529
  src/commands/config.js
  src/commands/set.js
  src/index.js
  src/utils/api.js
  src/utils/config.js
  src/utils/print.js
  test/specs/commands/config.js
  test/specs/commands/set.js
  test/specs/utils/api.js
  test/specs/utils/config.js
  test/specs/utils/helpers.js
  test/steps/child_processes/1_given.js
  test/steps/config/1_given.js
  test/steps/config/2_when.js
  test/steps/config/3_then.js
  test/steps/files/1_given.js
  test/steps/files/3_then.js
  test/steps/general/1_given.js
  test/steps/general/2_when.js
  test/steps/inputs/1_given.js
  test/steps/printing/3_then.js
  test/steps/setup.js
Labels: ✅ ready
